[project]
name = "qq-summarizer-bot"
version = "0.1.0"
description = "A bot who could summary QQ group messages"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.4.4",
    "langchain-chroma>=1.1.0",
    "langchain-openai>=1.7.0",
    "openai>=3.26.1",
    "python-dotenv>=1.2.4",
    "qq-botpy>=1.2.1",
]

[project.scripts]
qqbot = "scripts.cli:main"

[tool.setuptools.packages.find]
include = ["scripts*", "src*"]

[tool.uv]
package = true
